<?php

namespace App\Policies;

use App\Models\CooperationAgreement;
use App\Models\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class CooperationAgreementPolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view any models.
     */
    public function viewAny(User $user): bool
    {
        // Only Admins can view the entire list of SPKs
        return $user->role && $user->role->name === 'Admin';
    }

    /**
     * Determine whether the user can view the model.
     */
    public function view(User $user, CooperationAgreement $spk): bool
    {
        if ($user->role && $user->role->name === 'Admin') {
            return true;
        }

        // Organizers can view their own SPK
        $organizerProfile = $user->organizerProfile;
        
        return $organizerProfile && $organizerProfile->id === $spk->organizer_profile_id;
    }

    /**
     * Determine whether the user can create models.
     */
    public function create(User $user): bool
    {
        // Typically SPKs are generated by the system automatically or by Admin
        return $user->role && $user->role->name === 'Admin';
    }

    /**
     * Determine whether the user can update the model.
     */
    public function update(User $user, CooperationAgreement $spk): bool
    {
        // Only Admins have full access to modify the SPK document data
        return $user->role && $user->role->name === 'Admin';
    }

    /**
     * Determine whether the user can delete the model.
     */
    public function delete(User $user, CooperationAgreement $spk): bool
    {
        return $user->role && $user->role->name === 'Admin';
    }

    /**
     * Determine whether the user can digitally sign the SPK.
     */
    public function sign(User $user, CooperationAgreement $spk): bool
    {
        // Only the exact Organizer who owns this SPK is authorized to sign it
        $organizerProfile = $user->organizerProfile;
        
        return $organizerProfile && $organizerProfile->id === $spk->organizer_profile_id;
    }

    /**
     * Determine whether the user can verify (approve, request revision, reject) the SPK.
     */
    public function verify(User $user, CooperationAgreement $spk): bool
    {
        // Only Admin can verify/approve/reject SPK documents
        return $user->role && $user->role->name === 'Admin';
    }
}
